version: '3.8'

services:
  api:
    build:
      context: ./api-provisioner
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/terraform_provisioner
      - TERRAFORM_DIR=/app/terraform-workspaces
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_REGION=us-east-1
      - GIT_USERNAME=
      - GIT_PAT=
    volumes:
      - ./api-provisioner:/app
      - ./aws-gcp-terraform-weather-app:/app/aws-gcp-terraform-weather-app
      - terraform-workspaces:/app/terraform-workspaces
    depends_on:
      - db
    command: npm run dev

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=terraform_provisioner
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  terraform-workspaces:
