apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aws-gcp-provisioner.fullname" . }}-api-secret
  labels:
    {{- include "aws-gcp-provisioner.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.api.secrets }}
  {{ $key | lower | replace "_" "-" }}: {{ $value | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aws-gcp-provisioner.fullname" . }}-db-secret
  labels:
    {{- include "aws-gcp-provisioner.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ include "aws-gcp-provisioner.databaseUrl" . | b64enc | quote }}
